export const PRODUCT_LIST_LOAD = "PRODUCT_LIST_LOAD";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_DETAILS_LOAD = "PRODUCT_DETAILS_LOAD";
export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS";
export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL";

export const PRODUCT_ADD_LOAD = "PRODUCT_ADD_LOAD";
export const PRODUCT_ADD_SUCCESS = "PRODUCT_ADD_SUCCESS";
export const PRODUCT_ADD_FAIL = "PRODUCT_ADD_FAIL";

export const PRODUCT_RATE_LOAD = "PRODUCT_RATE_LOAD";
export const PRODUCT_RATE_SUCCESS = "PRODUCT_RATE_SUCCESS";
export const PRODUCT_RATE_FAIL = "PRODUCT_RATE_FAIL";
